main: main.c
	aarch64-linux-gnu-gcc main.c -o main -g3

# dump with hints to C file
# --- aarch64-linux-gnu-objdump -d -S main | less

# example to use export script
# aarch64-linux-gnu-objdump -d main > dump
# ./exportfun.py dump wc_AesEncryptSimplified test.ml
